### ISSUE TITLE
Change media in current call

### ISSUE THREAD

**Issue by martinbomio** [stephenlb/webrtc-sdk#14]
Hi, is there a way to change the media in the phone without instantiating a new PHONE instance?
Something like:
```
var phone = PHONE({number: "1234", media: { audio : true, video : false }});
phone.dial("567");
phone.media({ audio : true, video : true })
```

**Comment by stephenlb** [comment]
Hi Martin! currently a way does not exist.  You need to make a new phone
instance.

**Comment by martinbomio** [comment]
Thanks Stephen! Do you think this is doable? If so, I can try to implement it. Not sure if it's possible to change the stream in the peer connection. I see it is added this way:
```
            // Add Local Media Streams Audio Video Mic Camera
            talk.pc.addStream(mystream);
```

**Comment by stephenlb** [comment]
Hi Martin,  I am not totally sure if that will do the trick.

On Sun, Nov 29, 2015 at 12:45 PM, Martin <notifications@github.com> wrote:

> Thanks Stephen! Do you think this is doable? If so, I can try to implement
> it. Not sure if it's possible to change the stream in the peer connection.
> I see it is added this way:
>
>             // Add Local Media Streams Audio Video Mic Camera
>             talk.pc.addStream(mystream);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stephenlb/webrtc-sdk/issues/14#issuecomment-160469823>
> .
>



-- 
Cheers!
Stephen Blum - CTO
http://twitter.com/PubNub
https://github.com/pubnub/pubnub-api - GitHub
https://help.pubnub.com/ - Help Desk
www.pubnub.com
+1-425-830-6711
