### ISSUE TITLE
reject the call

### ISSUE THREAD

**Issue by d-knafo** [stephenlb/webrtc-sdk#22]
hi @stephenlb , 
I want to know if it is possible to reject a call ?
(a confirmation to enter in conversation)

**Comment by stephenlb** [comment]
Yes but you have to add this yourself.  There is no "ringer" or "calling" state.  Only an instant "connecting" state.

**Comment by Hamadme50** [comment]
stephenlb can you guide us how we can do it?

**Comment by stephenlb** [comment]
You can do this.  Here is an example.

```javascript
    // When Call Comes In or is to be Connected
    phone.receive(function(session){

        // immediately reject the call.   <--------------
        if (true) session.end();

        // Display Your Friend's Live Video
        session.connected(function(session){
            phone.$('video-out').appendChild(session.video);
        });

    });
```
