### ISSUE TITLE
Sound Volume

### ISSUE THREAD

**Issue by yvain99** [stephenlb/webrtc-sdk#25]
How can I decrease the volume / turn off loudspeaker of receiving calls?
It's like we turn on the loudspeaker on call received.

**Comment by stephenlb** [comment]
Callers must be in SEPARATE ROOMS. Calling devices are TOO CLOSE.  Make sure to use separate rooms.

**Comment by stephenlb** [comment]
You can also use the video volume on receivers like this:

Example
========

Set video volume to 20%:

```javascript
var vid = document.getElementById("myVideo");
vid.volume = 0.2;
```

reference: http://www.w3schools.com/tags/av_prop_volume.asp
