### ISSUE TITLE
appendChild JS error

### ISSUE THREAD

**Issue by Danny-Engelman** [stephenlb/webrtc-sdk#37]
I get this in Chrome:

![](http://i.imgur.com/KuYLgpK.jpg)

**Comment by stephenlb** [comment]
`img_self` must be undefined.  can you send me a link?  I will help you solve this.

**Comment by Danny-Engelman** [comment]
It happens on https://stephenlb.github.io/webrtc-sdk/?number=597 when you click the green camera button

Tried an Ingonito window, got: https://stephenlb.github.io/webrtc-sdk/?number=505

same error

Chrome: 58.0.3029.110

Same in Chrome Canary:

![](http://i.imgur.com/vX6D6hB.jpg)

**Comment by stephenlb** [comment]
Good find!  This will be fixed shortly.

**Comment by stephenlb** [comment]
This is fixed! - https://github.com/stephenlb/webrtc-sdk/commit/248c2cf80a69ed5c6fc99f8f37714d6c9ad8a46f
