### ISSUE TITLE
Broadcast resolution

### ISSUE THREAD

**Issue by the-interactive-company** [stephenlb/webrtc-sdk#38]
Is there a way to limit the Broadcasted Resoultion?
My camera or any camera lately is 4K ultra HD at 1000000x300000 or whatever. That size doesn't go down the comcast wires all that well. Especially on mobile.  

I'm using and messing around and testing your basic install but with the V2 .js.  What and where would I edit to restrict the broadcast video size to something other then default... whatever the default is.  I'm at a loss to where that can be controlled.   

Thank you.

**Comment by stephenlb** [comment]
# Set Camera Resolution

You can change the resolution of your camera's media capture.  This allows you to set lower resolutions for slower p2p connections.  You can also set HD 4K resolutions if you have the camera to do so.

```javascript
// Phone
const phone = PHONE({
    number        : number
,   media         : { video: { width:1280, height:720 } } // <---- change resolution
,   publish_key   : pubkey
,   subscribe_key : subkey 
});
```
