### ISSUE TITLE
WebRTC SDK doesn't support Pubnub V4

### ISSUE THREAD

**Issue by techmanha** [stephenlb/webrtc-sdk#39]
The webrtc.js doesn't work with Pubnub v4
https://cdn.pubnub.com/sdk/javascript/pubnub.4.12.0.js

**Comment by stephenlb** [comment]
The PubNub SDK has been removed in V2.  You do not need to use the PubNub SDK with https://github.com/stephenlb/webrtc-sdk/blob/master/js/webrtc-v2.js
