### ISSUE TITLE
Android Native Support

### ISSUE THREAD

**Issue by adityaxavier** [stephenlb/webrtc-sdk#40]
Hello,
In the Readme file its written that Android Native Java is supported, but I fail to understand how. 

"WebRTC calling on Android is web-ready compatible and works out-of-the-box today without modifications or additional code. Also WebRTC Calling is supported for Android and iOS Native too."

Could you please enlighten how that works ?

**Comment by alejo-moreno** [comment]
#45

**Comment by stephenlb** [comment]
According to the documentation "The PubNub Android WebRTC Signaling API is fully compatible with the PubNub JavaScript WebRTC SDK. This means that browser to mobile communication is simple!"

https://github.com/GleasonK/android-webrtc-api
