### ISSUE TITLE
Safari 11 issues

### ISSUE THREAD

**Issue by kailasvnair** [stephenlb/webrtc-sdk#42]

**Comment by kailasvnair** [comment]
Web rtc not working in safari 11

**Comment by stephenlb** [comment]
Are you using HTTPS?  Make sure to use HTTPS when testing.

### Testing Locally

You need an HTTPS (TLS) File Server. To start a local secure file server:

```shell
python <(curl -L https://goo.gl/LiW3lp)
```

Then open your browser and point it to your file in
the directory you ran the python HTTPS server.

```shell
open https://0.0.0.0:4443/your-file-here.html
```

> This is a Simple Python HTTPS Secure Server
> https://gist.github.com/stephenlb/2e19d98039469b9d0134

We posted an answer on
[StackOverflow WebRTC HTTPS](http://stackoverflow.com/a/41969170/524733).
This will get you started testing on your laptop.

**Comment by stephenlb** [comment]
Safari isn't current working.  The WebRTC Support should allow it to work.  However it currently does not.
