### ISSUE TITLE
phone.stop() is not working

### ISSUE THREAD

**Issue by bryanlimy** [stephenlb/webrtc-sdk#44]
I tried on both v1 and v2, `phone.stop()` would be get me `TypeError: phone.stop is not a function`.

I wonder if there is a probably to terminate a `PHONE` and stop using the camera/mic.

**Comment by stephenlb** [comment]
Checking...

**Comment by stephenlb** [comment]
Try: `PHONE.camera.stop` or `phone.camera.stop`.

Looks like only the `session` also has this method. Try using `session.stop()`.  I'll update the docs to reference this correctly.

**Comment by stephenlb** [comment]
For code reference detail on Camera/Mic Media Access:

```javascript
PHONE.camera.start = startcamera;
PHONE.camera.stop  = stopcamera;
PHONE.camera.video = () => myvideo;
PHONE.camera.ready = PHONE.camera;
```

**Comment by bryanlimy** [comment]
just tested

`phone.camera.stop()` works fine. it stops the `MediaStreamTrack`

Thanks!
