### ISSUE TITLE
Native android java example

### ISSUE THREAD

**Issue by 28development** [stephenlb/webrtc-sdk#45]
Hi,

This repository works great so far. In my case we need to create this video call from a webbrowser to a native android app. I could not find a proper native android example for this case.
Could you tell me if there is one?

Best regards.

**Comment by alejo-moreno** [comment]
According to the documentation "The PubNub Android WebRTC Signaling API is fully compatible with the PubNub JavaScript WebRTC SDK. This means that browser to mobile communication is simple!"  

Here is the [project](https://github.com/GleasonK/android-webrtc-api)

**Comment by 28development** [comment]
Hi,

I set up the android application but I am not able to find to suitable webapplication source code/repository.

Best regards

**Comment by alejo-moreno** [comment]
@28development You mean the Web SDK version of this? If so, check out [this](https://github.com/stephenlb/webrtc-sdk)

**Comment by 28development** [comment]
Issue can be removed
