### ISSUE TITLE
Not working in ios

### ISSUE THREAD

**Issue by Hamadme50** [stephenlb/webrtc-sdk#48]
tested ios latest version and older not working

**Comment by stephenlb** [comment]
Confirmed.  Looks like iOS 11 supports WebRTC. however our SDK isn't working with it right now.  WebRTC Support reference article: https://flashphoner.com/ios-safari-11-now-supports-webrtc/

We are investigating a way to make this work.

**Comment by Hamadme50** [comment]
thanks dear waiting for it

**Comment by stephenlb** [comment]
https://stackoverflow.com/questions/48652714/ios-11-simulator-safari-getusermedia-invalid-constraint

**Comment by stephenlb** [comment]
Trying to get this to work on the iOS simulator.  And the iOS **Simulator is not Simulating!!!**

**Comment by stephenlb** [comment]
Confirmed.  iOS Simulator doesn't support WebRTC.  We need to find an iOS 11 device to add this feature.

**Comment by stephenlb** [comment]
We are collecting details on making this work.  Sprint complete in next two weeks.

**Comment by stephenlb** [comment]
Fixed!  Use the latest version of `webrtc.js` here: https://stephenlb.github.io/webrtc-sdk/js/webrtc.js

**Comment by Hamadme50** [comment]
getting error
webrtc.js:571 Uncaught TypeError: this.mergeJSON is not a function
    at merge (v3.js:571)
    at window.PHONE (v3.js:13)
    at (index):624

**Comment by Hamadme50** [comment]
getting error
webrtc.js:571 Uncaught TypeError: this.mergeJSON is not a function
    at merge (webrtc.js:571)
    at window.PHONE (webrtc.js:13)
    at (index):624

**Comment by stephenlb** [comment]
Thank you!  checking....

**Comment by stephenlb** [comment]
Fixed.

**Comment by stephenlb** [comment]
Fix is applied and live: https://github.com/stephenlb/webrtc-sdk/commit/4ed5867aa97f45040678ae41a6a07252c36aea6c

**Comment by Hamadme50** [comment]
Now it us working in ios great job thanks

**Comment by stephenlb** [comment]
🎉
