### ISSUE TITLE
Issue in windows 7 latest chrome

### ISSUE THREAD

**Issue by Hamadme50** [stephenlb/webrtc-sdk#49]
i just test it on windows 7 chrome and it is not working in windows 7 latest chrome

**Comment by stephenlb** [comment]
Thank you!  Do you have the URL you tested?

**Comment by Hamadme50** [comment]
i have made a [Pakistani chat rooms](https://www.livechatzone.com) chatting site i have implement your Webetc sdk in it. i will sent you test user credentials to test it. thanks

**Comment by stephenlb** [comment]
Hi!  It looks like it is working.  All packets are exchanged successfully.  However it seems that the audio is not being bound to a render element.  You may be missing a step in your usage.  Can you test to see if it works on this page: https://stephenlb.github.io/webrtc-sdk/ with chrome on windows 7?  This is a good demo which is a known working demo.

**Comment by Hamadme50** [comment]
I have tested i have windows 10 it is working fine with even my own url above. Now the issue is some of my users useing windows 7 and able to do audio i have checked their system with team-viewer they are on latest chrome.

**Comment by stephenlb** [comment]
This WebRTC SDK will not work with audio if one of the users is on a Double NAT.  You will need to find a TURN SERVER to broker the audio connection in this case.  https://xirsys.com/ is a good provider of TURN SERVERS for WebRTC Audio/Video brokering.

**Comment by Hamadme50** [comment]
Thanks i will test it
