### ISSUE TITLE
Mac - Safari. TypeError: talk.pc.addStream is not a function.

### ISSUE THREAD

**Issue by crookedbard** [stephenlb/webrtc-sdk#56]
On iOS Safari everything works fine, but on Mac Safari I get this error:
`TypeError: talk.pc.addStream is not a function. (In 'talk.pc.addStream(mystream)', 'talk.pc.addStream' is undefined) (anonymous function) — webrtc.js:196 get_conversation — webrtc.js:204 dial — webrtc.js:251 dial — webrtc-sdk:200 (anonymous function) — webrtc-sdk:220 onready — webrtc.js:401 connect — webrtc.js:392 (anonymous function) — pubnub.js:1129 (anonymous function) — pubnub.js:568 each — pubnub.js:297 each_channel — pubnub.js:562 success — pubnub.js:1126 finished — pubnub.js:2996 Selected Element <div id="pubnub-chat-output">…</div>`

**Comment by stephenlb** [comment]
just tested seems to work!  what version?

![screen shot 2018-10-09 at 11 19 30 am](https://user-images.githubusercontent.com/45214/46689633-35fb9780-cbb5-11e8-93c1-be83601dc269.png)

**Comment by crookedbard** [comment]
![](https://i.imgur.com/oE3tW8x.png)

navigator.getUserMedia got deprecated, you need to use navigator.mediaDevices.getUserMedia and there may be some RTPPeerConnection changes

**Comment by stephenlb** [comment]
patched and pushed.  https://github.com/stephenlb/webrtc-sdk/commit/5935d883deec12193fd1a5a06dd1d19cf9a10715
