### ISSUE TITLE
Deprecated. URL.createObjectURL

### ISSUE THREAD

**Issue by crookedbard** [stephenlb/webrtc-sdk#57]
URL.createObjectURL with media streams is deprecated and will be removed in M71, around December 2018. Please use HTMLMediaElement.srcObject instead.

**Comment by stephenlb** [comment]
Nice!  Will add this fix.

**Comment by stephenlb** [comment]
fixed: https://github.com/stephenlb/webrtc-sdk/commit/3494723191cd305d205d5dca1fbff2a216717531
