### ISSUE TITLE
Sometimes session.video is whitout a stream

### ISSUE THREAD

**Issue by crookedbard** [stephenlb/webrtc-sdk#58]
When I do repeat calls to: dial and hang-up after several tries I don’t get the video stream. Repeating the calls one more time usually fixes it.

**Comment by stephenlb** [comment]
If you are using V2, this is a known issue we have not been able to solve.  V1 however does not seem to have this issue.

**Comment by stephenlb** [comment]
Also we've made some recent upgrades to V2 and you may see that these patches reduces the false video streams.

**Comment by crookedbard** [comment]
Where can I find V1? and will it work the same as V2 or do I need to reimplement V1 from the start?

**Comment by crookedbard** [comment]
When i try to use webrtc.js instread webrtc-v2.js I get such error:
Uncaught ReferenceError: PUBNUB is not defined
    at window.PHONE (webrtc.js:17)

**Comment by crookedbard** [comment]
session.video.onloadedmetadata
Does not get called when there is no video in stream.

**Comment by stephenlb** [comment]
Thank you for reporting these details!  V1 webrtc.js requires PubNub v3 sdk.

https://cdn.pubnub.com/pubnub.min.js

**Comment by stephenlb** [comment]
Working to fix V2

**Comment by stephenlb** [comment]
V2 has been improved with consistency.

**Comment by crookedbard** [comment]
Chrome to chrome video still freezes.
Caller A calls Caller B, A video is normal on both callers but B video is frozen on both callers.

**Comment by stephenlb** [comment]
This should be fixed with the recent race condition fix patch.

**Comment by crookedbard** [comment]
Still testing this fix, seems to be working far better now 👍 For now I will close this issue.
