### ISSUE TITLE
Safari 12 issue. The browser doesn't receive the call

### ISSUE THREAD

**Issue by crookedbard** [stephenlb/webrtc-sdk#59]
Camera turns on, but session.connected doesn't get called.

**Comment by crookedbard** [comment]
`TypeError: Member RTCIceServer.urls is required and must be an instance of (DOMString or sequence)
(anonymous function) — webrtc-v2.js:400
initializeRTCPeerConnection
(anonymous function)
(anonymous function) — webrtc-v2.js:400
get_conversation — webrtc-v2.js:465
dial — webrtc-v2.js:556
(anonymous function) — videocall:463
dispatch — jquery:1:50834
2success — videocall:580`

**Comment by stephenlb** [comment]
Okay, so I removed the Safari errors.  However the video stream does not play.

**Comment by crookedbard** [comment]
I see some progress :)

Tested on: 
Caller A: iOS Safari
Caller B: Windows Chrome 

Caller A and B now gets the messages sent between them. 
Caller A doesn't see any video, nor local nor B, but hears the sound.
Caller B sees local video, A video is always frozen at first frame .

**Comment by stephenlb** [comment]
Will continue working on this.

**Comment by stephenlb** [comment]
getting closer...

**Comment by stephenlb** [comment]
Getting a lot closer!  Safari 12 can send/receive calls to any other browser!  However Safari is still unable to call Safari successfully.

**Comment by stephenlb** [comment]
Apple’s WebRTC implementation only allows one getUserMedia capture at a time.  So this is why I've never been able to get Safari to work.  However when testing across computers we do see it works successfully.

**Comment by stephenlb** [comment]
Just submitted the next release with a much needed race condition fix on signaling exchanges.  This may have improved the conditions you mentioned.

**Comment by crookedbard** [comment]
Safari to Chrome works now 👍
