### ISSUE TITLE
Video always freezes!

### ISSUE THREAD

**Issue by crookedbard** [stephenlb/webrtc-sdk#61]
Pubnub server started to freeze videos.
From 2018-10-17 
UTC 2:00 PM

**Comment by crookedbard** [comment]
It seems yesterday changes made the video freeze, not only on iOS Safari but on all browsers.

**Comment by stephenlb** [comment]
Will be working on this to resolve.

**Comment by stephenlb** [comment]
getting closer...

**Comment by stephenlb** [comment]
Getting a lot closer!  Safari 12 can send/receive calls to any other browser!  However Safari is still unable to call Safari successfully.

**Comment by crookedbard** [comment]
We had issues when calling from chrome to mozzila fire fox? We used to get cross origin issue.

**Comment by stephenlb** [comment]
Apple’s WebRTC implementation only allows one getUserMedia capture at a time.  So this is why I've never been able to get Safari to work.

**Comment by stephenlb** [comment]
Video Freezing: https://blog.mozilla.org/webrtc/when-your-video-freezes/ - this may be the fix

**Comment by crookedbard** [comment]
Windows OS: Chrome to Chrome video still freezes.
Caller A calls Caller B, A video is normal on both callers but B video is frozen on both callers.

**Comment by crookedbard** [comment]
Caller A debug log:
![image](https://user-images.githubusercontent.com/4722359/47205016-7e713d00-d38d-11e8-972a-859925f47472.png)
Caller B debug log:
![image](https://user-images.githubusercontent.com/4722359/47205045-8d57ef80-d38d-11e8-9d4c-50964cc60ce8.png)

**Comment by stephenlb** [comment]
Just submitted the next release with a much needed race condition fix on signaling exchanges.  This may have improved the conditions you see.

**Comment by crookedbard** [comment]
I just checked it. Still same issue. Tested on Chrome Version 69.0.3497.100 (Official Build) (64-bit). Before commit 12793d666437dc80dbfd3d7d3d0b8230de3d840f video wouldn't freeze but now it does.
I use both local video cam and callers video cam on both sides of the connection. So the caller sees itself and the participant, same at the participants end. Callers video is not frozen on both the callers (local) side and the participants, but the participants video is frozen on local and callers side.

**Comment by crookedbard** [comment]
Ok I found the issue. To ensure that the video will be shown I had this code before:

`var videoStreamActive = false;
phone.receive(function(session) {
                console.log('receive');

                
	// Display Your Friend's Live Video
	session.connected(function (session) {

		// Work arround the issue when the video is not always shown.
		session.video.srcObject.onaddtrack = function(event) {
								videoStreamActive = true;
							};

		session.video.srcObject.oninactive = function(event) {
			videoStreamActive = false;
		};

		session.video.onloadedmetadata = function(e) {
			if (videoStreamActive) {
				//video is always shown.
				onVideoCallNow = true;

				video.appendChild(session.video);
			}
		};
		
});`

But now because of this code the video of participants is always frozen. When I remove this then the video is not frozen, but I need to ensure that the video will always be shown to the user.
