### ISSUE TITLE
Do you have a solution for echo cancellation?

### ISSUE THREAD

**Issue by popdance** [stephenlb/webrtc-sdk#9]
We found one problem while implement the WebRTC.
It's Echo. I think that due to transfer my voice data.

Do you have a solution for echo cancellation?

Thanks!

**Comment by stephenlb** [comment]
NOPE!  WebRTC native will eventually add this.

**Comment by popdance** [comment]
Thank you for your response.
Have a good day!

2016-07-19 4:40 GMT+09:00 Stephen L. Blum <notifications@github.com>:
